[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/coconutbird/cppvtable"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

[workspace.dependencies]
cpp = "0.5"
cpp_build = "0.5"
cppvtable = { version = "0.1.0", path = "crates/cppvtable" }
cppvtable-macro = { version = "0.1.0", path = "crates/cppvtable-macro" }
paste = { package = "pastey", version = "0.2.3" }
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full", "extra-traits"] }
windows-core = "0.62"
