[package]
name = "cppvtable"
version.workspace = true
edition.workspace = true
description = "C++ vtable interop for Rust (MSVC ABI compatible)"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
windows-compat = ["dep:windows-core"]

[dependencies]
cppvtable-macro = { workspace = true }
paste = { workspace = true }
windows-core = { workspace = true, optional = true }
