//! Stable C/C++ object allocations without reference counting.

use alloc::boxed::Box;
use core::any::{TypeId, type_name};
use core::ffi::c_void;
use core::fmt;
use core::mem::offset_of;
use core::ops::Deref;
use core::ptr::NonNull;

use crate::{Interface, InterfaceRef, VtablePtr};

/// Physical interface properties used when attaching C++ RTTI to an object.
#[derive(Clone, Copy, Debug)]
pub struct InterfaceDescriptor {
    /// Whether the object holds a pointer or inline table entries.
    pub layout: crate::VtableLayout,
    /// Native C++ ABI, or `None` for C interfaces.
    pub cpp_abi: Option<crate::rtti::CppAbi>,
    /// Size of the declared function table in bytes, including reserved entries.
    pub table_size: usize,
    /// Alignment of the declared function table.
    pub table_align: usize,
}

/// Metadata for a C/C++ interface and its prefix-compatible base interfaces.
///
/// The [`crate::interface`] macro implements this trait.
///
/// # Safety
///
/// `matches_type` may identify only `Self` and interfaces whose vtables are compatible
/// prefixes of `Self::Vtbl`, with the same interface pointer representation and layout.
/// `Storage` must have the representation selected by `Self::LAYOUT`: one vtable
/// pointer, or a nonempty inline `Self::Vtbl`. `storage` must preserve the supplied
/// table's entries and may not retain or create ownership of anything else.
pub unsafe trait CppInterface: Interface {
    /// Object header for this interface: a vtable pointer or inline table entries.
    type Storage: Copy + Send + Sync + 'static;

    /// Initialize an object's interface header from its static table template.
    fn storage(vtable: &'static Self::Vtbl) -> Self::Storage;

    /// Whether this interface chain can be borrowed as the interface identified by `id`.
    fn matches_type(id: TypeId) -> bool;
}

/// Static vtable layout generated by [`crate::implement`].
///
/// # Safety
///
/// `Vtables` must be a nonempty C-layout header containing one interface storage
/// field per entry of `SLOT_OFFSETS`, `INTERFACES`, and `vtable_slots`; all three
/// lists must have equal lengths. Each descriptor must give the exact layout, C++ ABI,
/// table size, and table alignment of its interface. The offsets must identify
/// those fields in order, with the primary interface at zero. Each field must use
/// its interface's declared layout and the corresponding static table's entries.
/// Every shim must adjust `this` to the correct [`Object<Self>`]. `slot_for_type`
/// must return only valid, prefix-compatible interface slots.
pub unsafe trait Implement: Sized + 'static {
    /// Interface headers stored at the beginning of the object.
    type Vtables: Copy + Send + Sync + 'static;
    /// Interface of the first vtable pointer.
    type Primary: CppInterface;
    /// Byte offsets of each interface header, in declaration order.
    const SLOT_OFFSETS: &'static [usize];
    /// Physical properties for each interface in declaration order.
    const INTERFACES: &'static [InterfaceDescriptor];
    /// Initial interface headers for a new object.
    fn vtables() -> Self::Vtables;
    /// Addresses of the static table templates, in interface order.
    ///
    /// Inline tables are copied from these templates into each object.
    fn vtable_slots() -> &'static [VtablePtr];
    /// Locate an implemented interface or one of its prefix-compatible ancestors.
    fn slot_for_type(id: TypeId) -> Option<usize>;
}

/// A directly implemented interface at a known interface header index.
///
/// # Safety
///
/// `SLOT` must identify an entry whose vtable is compatible with `I::Vtbl`.
pub unsafe trait Implements<I: CppInterface>: Implement {
    /// Index of the interface chain in the object.
    const SLOT: usize;
}

/// A C/C++ object consisting of interface headers followed by its Rust value.
///
/// Allocate using [`OwnedObject::new`]. Each interface header contains either a
/// pointer to a static table or inline table entries, as declared by that interface.
/// Secondary interface chains have their own headers in this allocation.
#[repr(C)]
pub struct Object<T: Implement> {
    vtables: T::Vtables,
    data: T,
}

impl<T: Implement> Object<T> {
    /// Borrow the implementation value.
    #[must_use]
    pub fn data(&self) -> &T {
        &self.data
    }

    /// Byte offset of the specified interface chain's header.
    ///
    /// Panics if `slot` is not a declared interface index.
    #[must_use]
    pub const fn slot_offset(slot: usize) -> usize {
        offset_of!(Self, vtables) + T::SLOT_OFFSETS[slot]
    }

    /// Get a raw interface pointer from a live object allocation.
    ///
    /// # Safety
    ///
    /// `object` must point to a live `Object<T>` and `slot` must be a valid slot.
    #[must_use]
    pub unsafe fn slot_ptr(object: *const Self, slot: usize) -> *mut c_void {
        unsafe {
            object
                .cast::<u8>()
                .add(Self::slot_offset(slot))
                .cast_mut()
                .cast()
        }
    }

    /// Recover an object from one of its interface chain pointers.
    ///
    /// # Safety
    ///
    /// `this` must point to the interface header in slot `slot` of a live `Object<T>`.
    /// The object must remain alive for the returned reference's lifetime.
    #[must_use]
    pub unsafe fn from_slot<'a>(this: *mut c_void, slot: usize) -> &'a Self {
        unsafe {
            &*this
                .cast::<u8>()
                .sub(Self::slot_offset(slot))
                .cast::<Self>()
        }
    }

    /// Recover the implementation value for a generated vtable shim.
    ///
    /// # Safety
    ///
    /// See [`Self::from_slot`].
    #[must_use]
    pub unsafe fn impl_from_slot<'a>(this: *mut c_void, slot: usize) -> &'a T {
        unsafe { Self::from_slot(this, slot) }.data()
    }

    /// Recover the allocation address from its implementation field.
    ///
    /// # Safety
    ///
    /// `data` must be the actual field of a live `Object<T>`, not a standalone value.
    #[must_use]
    pub unsafe fn of_data(data: &T) -> *const Self {
        unsafe {
            core::ptr::from_ref(data)
                .cast::<u8>()
                .sub(offset_of!(Self, data))
                .cast()
        }
    }

    /// Destroy an allocation previously relinquished by [`OwnedObject::into_raw`].
    ///
    /// # Safety
    ///
    /// The pointer must own the sole allocation ownership. No caller may access the
    /// object after destruction, and no borrowed interface may remain live.
    pub unsafe fn destroy(object: *const Self) {
        drop(unsafe { Box::from_raw(object.cast_mut()) });
    }
}

/// Sole ownership of a stable C/C++ object allocation.
///
/// Dereferences to the implementation value.
///
/// The object is destroyed once when this handle is dropped. Foreign code may borrow
/// its raw interfaces while the handle is alive; lifetime and thread rules for those
/// raw pointers remain the caller's responsibility.
pub struct OwnedObject<T: Implement> {
    object: NonNull<Object<T>>,
}

impl<T: Implement> OwnedObject<T> {
    /// Allocate the object and initialize its static vtable pointers.
    #[must_use]
    pub fn new(value: T) -> Self {
        Self::with_headers(T::vtables(), value)
    }

    /// Allocate with prepared interface headers, such as those of an RTTI class.
    pub(crate) fn with_headers(vtables: T::Vtables, data: T) -> Self {
        let object = Box::into_raw(Box::new(Object { vtables, data }));
        Self {
            // SAFETY: `Box::into_raw` never returns null.
            object: unsafe { NonNull::new_unchecked(object) },
        }
    }

    /// Borrow a directly implemented interface.
    #[must_use]
    pub fn interface<I: CppInterface>(&self) -> InterfaceRef<'_, I>
    where
        T: Implements<I>,
    {
        self.borrow_slot(<T as Implements<I>>::SLOT)
    }

    /// Borrow an implemented interface or a prefix-compatible base interface, or
    /// `None` if `T` implements neither.
    ///
    /// Lookup uses Rust type identity; it is not COM `QueryInterface`.
    #[must_use]
    pub fn try_interface<I: CppInterface>(&self) -> Option<InterfaceRef<'_, I>> {
        T::slot_for_type(TypeId::of::<I>()).map(|slot| self.borrow_slot(slot))
    }

    /// Get a directly implemented interface's pointer for a foreign caller.
    #[must_use]
    pub fn as_raw<I: CppInterface>(&self) -> *mut c_void
    where
        T: Implements<I>,
    {
        // SAFETY: The handle keeps the allocation live and `Implements` gives a valid slot.
        unsafe { Object::<T>::slot_ptr(self.object.as_ptr(), <T as Implements<I>>::SLOT) }
    }

    /// Transfer allocation ownership to a raw pointer.
    ///
    /// Reclaim it with [`Self::from_raw`] or [`Object::destroy`]. The pointer is the
    /// allocation address, which is also the primary interface address.
    #[must_use]
    pub fn into_raw(self) -> *mut Object<T> {
        let pointer = self.object.as_ptr();
        core::mem::forget(self);
        pointer
    }

    /// Reclaim allocation ownership from a raw pointer.
    ///
    /// # Safety
    ///
    /// `object` must come from [`Self::into_raw`] and still uniquely own a live
    /// allocation. No other owning handle may exist.
    #[must_use]
    pub unsafe fn from_raw(object: *mut Object<T>) -> Self {
        Self {
            // SAFETY: The caller supplies a pointer from `into_raw`, which is never null.
            object: unsafe { NonNull::new_unchecked(object) },
        }
    }

    fn borrow_slot<I: CppInterface>(&self, slot: usize) -> InterfaceRef<'_, I> {
        // SAFETY: The handle keeps the allocation live and callers pass a valid slot
        // whose header is compatible with `I`. The pointer lies inside a non-null
        // allocation, and the returned borrow cannot outlive the handle.
        unsafe {
            let pointer = Object::<T>::slot_ptr(self.object.as_ptr(), slot);
            InterfaceRef::from_non_null(NonNull::new_unchecked(pointer))
        }
    }
}

impl<T: Implement> Deref for OwnedObject<T> {
    type Target = T;

    fn deref(&self) -> &T {
        // SAFETY: The handle uniquely owns a live allocation for its whole lifetime.
        unsafe { self.object.as_ref() }.data()
    }
}

impl<T: Implement> fmt::Debug for OwnedObject<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "OwnedObject<{}>({:p})",
            type_name::<T>(),
            self.object
        )
    }
}

impl<T: Implement> Drop for OwnedObject<T> {
    fn drop(&mut self) {
        // SAFETY: The handle solely owns the allocation, and every interface borrow
        // of the handle has ended.
        unsafe { Object::<T>::destroy(self.object.as_ptr()) };
    }
}

// SAFETY: This handle uniquely owns T; all interface views borrow the handle.
unsafe impl<T: Implement + Send> Send for OwnedObject<T> {}
// SAFETY: Shared handle methods expose only shared references to T.
unsafe impl<T: Implement + Sync> Sync for OwnedObject<T> {}

/// Borrow an interface of the object containing an implementation method's `self`.
///
/// Name only the interface, as in `interface_of::<IFoo>(self)`. The returned view's
/// `as_raw` gives the raw pointer for a foreign caller.
///
/// # Safety
///
/// `data` must be the implementation field inside a live [`Object`]. A standalone
/// instance of the implementation type does not satisfy this requirement.
#[must_use]
pub unsafe fn interface_of<I: CppInterface>(data: &impl Implements<I>) -> InterfaceRef<'_, I> {
    // SAFETY: The caller guarantees `data` is embedded in a live object.
    unsafe { embedded_interface(data) }
}

/// Name the implementation type hidden by `interface_of`'s `impl Trait` argument.
///
/// # Safety
///
/// See [`interface_of`].
unsafe fn embedded_interface<T: Implements<I>, I: CppInterface>(data: &T) -> InterfaceRef<'_, I> {
    // SAFETY: `data` lives in an `Object<T>`, so the recovered allocation is live for
    // the borrow of `data`, `Implements` gives a slot compatible with `I`, and the
    // header address inside that allocation is non-null.
    unsafe {
        let object = Object::<T>::of_data(data);
        let pointer = Object::<T>::slot_ptr(object, <T as Implements<I>>::SLOT);
        InterfaceRef::from_non_null(NonNull::new_unchecked(pointer))
    }
}
