//! Stable C/C++ object allocations without reference counting.

use core::any::TypeId;
use core::ffi::c_void;
use core::marker::PhantomData;
use core::mem::{offset_of, size_of};
use core::ops::Deref;
use core::ptr::NonNull;

use crate::{Interface, VtablePtr};

/// Metadata for a C/C++ interface and its prefix-compatible base interfaces.
///
/// The [`crate::interface`] macro implements this trait.
///
/// # Safety
///
/// `matches_type` may identify only `Self` and interfaces whose vtables are compatible
/// prefixes of `Self::Vtbl`, with the same interface pointer representation.
pub unsafe trait CppInterface: Interface {
    /// Whether this interface chain can be borrowed as the interface identified by `id`.
    fn matches_type(id: TypeId) -> bool;
}

/// Static vtable layout generated by [`crate::implement`].
///
/// # Safety
///
/// `Vtables` must be a nonempty `[VtablePtr; N]` whose entries exactly match
/// `vtable_slots`. Entry zero must use `Primary::Vtbl`. Every entry must point at an
/// immutable live vtable whose shims adjust `this` to the correct [`Object<Self>`].
/// `slot_for_type` must return only valid, prefix-compatible interface slots.
pub unsafe trait Implement: Sized + 'static {
    /// Contiguous vtable pointers stored at the beginning of the object.
    type Vtables: Copy + Send + Sync + 'static;
    /// Interface of the first vtable pointer.
    type Primary: CppInterface;
    /// Initial vtable pointers for a new object.
    fn vtables() -> Self::Vtables;
    /// Addresses of the static vtables, in slot order.
    fn vtable_slots() -> &'static [VtablePtr];
    /// Locate an implemented interface or one of its prefix-compatible ancestors.
    fn slot_for_type(id: TypeId) -> Option<usize>;
}

/// A directly implemented interface at a known vtable pointer slot.
///
/// # Safety
///
/// `SLOT` must identify an entry whose vtable is compatible with `I::Vtbl`.
pub unsafe trait Implements<I: CppInterface>: Implement {
    /// Index of the interface chain in the object.
    const SLOT: usize;
}

/// A C/C++ object consisting only of vtable pointers followed by its Rust value.
///
/// Allocate using [`OwnedObject::new`]. Interface pointers refer to fields of this
/// allocation, including secondary interface chains at later pointer slots.
#[repr(C)]
pub struct Object<T: Implement> {
    vtables: T::Vtables,
    data: T,
}

impl<T: Implement> Object<T> {
    /// Allocate an object with a stable address and return its owning handle.
    #[must_use]
    #[expect(
        clippy::new_ret_no_self,
        reason = "A foreign object needs a stable owning allocation."
    )]
    pub fn new(value: T) -> OwnedObject<T> {
        OwnedObject::new(value)
    }

    /// Borrow the implementation value.
    #[must_use]
    pub fn data(&self) -> &T {
        &self.data
    }

    /// Byte offset of the specified interface chain's vtable pointer.
    #[must_use]
    pub const fn slot_offset(slot: usize) -> usize {
        offset_of!(Self, vtables) + slot * size_of::<VtablePtr>()
    }

    /// Get a raw interface pointer from a live object allocation.
    ///
    /// # Safety
    ///
    /// `object` must point to a live `Object<T>` and `slot` must be a valid slot.
    #[must_use]
    pub unsafe fn slot_ptr(object: *const Self, slot: usize) -> *mut c_void {
        unsafe {
            object
                .cast::<u8>()
                .add(Self::slot_offset(slot))
                .cast_mut()
                .cast()
        }
    }

    /// Recover an object from one of its interface chain pointers.
    ///
    /// # Safety
    ///
    /// `this` must point to the vtable pointer in slot `slot` of a live `Object<T>`.
    /// The object must remain alive for the returned reference's lifetime.
    #[must_use]
    pub unsafe fn from_slot<'a>(this: *mut c_void, slot: usize) -> &'a Self {
        unsafe {
            &*this
                .cast::<u8>()
                .sub(Self::slot_offset(slot))
                .cast::<Self>()
        }
    }

    /// Recover the implementation value for a generated vtable shim.
    ///
    /// # Safety
    ///
    /// See [`Self::from_slot`].
    #[must_use]
    pub unsafe fn impl_from_slot<'a>(this: *mut c_void, slot: usize) -> &'a T {
        unsafe { Self::from_slot(this, slot) }.data()
    }

    /// Recover the allocation address from its implementation field.
    ///
    /// # Safety
    ///
    /// `data` must be the actual field of a live `Object<T>`, not a standalone value.
    #[must_use]
    pub unsafe fn of_data(data: &T) -> *const Self {
        unsafe {
            core::ptr::from_ref(data)
                .cast::<u8>()
                .sub(offset_of!(Self, data))
                .cast()
        }
    }

    /// Destroy an allocation previously relinquished by [`OwnedObject::into_raw`].
    ///
    /// # Safety
    ///
    /// The pointer must own the sole allocation ownership. No caller may access the
    /// object after destruction, and no borrowed interface may remain live.
    pub unsafe fn destroy(object: *const Self) {
        drop(unsafe { Box::from_raw(object.cast_mut()) });
    }
}

/// An interface value tied to the lifetime of its owning object.
///
/// Dereference to call interface methods. Unlike a raw pointer, this borrow prevents
/// the owning handle from being dropped while the interface is used.
pub struct InterfaceRef<'a, I: CppInterface> {
    interface: I,
    lifetime: PhantomData<&'a c_void>,
}

impl<I: CppInterface> Deref for InterfaceRef<'_, I> {
    type Target = I;

    fn deref(&self) -> &I {
        &self.interface
    }
}

impl<I: CppInterface> InterfaceRef<'_, I> {
    /// Get the borrowed interface pointer.
    #[must_use]
    pub fn as_raw(&self) -> *mut c_void {
        crate::raw_of(&self.interface)
    }
}

/// Sole ownership of a stable C/C++ object allocation.
///
/// The object is destroyed once when this handle is dropped. Foreign code may borrow
/// its raw interfaces while the handle is alive; lifetime and thread rules for those
/// raw pointers remain the caller's responsibility.
pub struct OwnedObject<T: Implement> {
    object: NonNull<Object<T>>,
}

impl<T: Implement> OwnedObject<T> {
    /// Allocate the object and initialize its static vtable pointers.
    #[must_use]
    pub fn new(value: T) -> Self {
        let object = Box::new(Object {
            vtables: T::vtables(),
            data: value,
        });
        Self {
            object: NonNull::from(Box::leak(object)),
        }
    }

    /// Borrow the Rust implementation value.
    #[must_use]
    pub fn get(&self) -> &T {
        unsafe { self.object.as_ref() }.data()
    }

    /// Borrow a directly implemented interface.
    #[must_use]
    pub fn interface<I: CppInterface>(&self) -> InterfaceRef<'_, I>
    where
        T: Implements<I>,
    {
        self.borrow_slot(<T as Implements<I>>::SLOT)
    }

    /// Borrow an implemented interface or a prefix-compatible base interface.
    ///
    /// Lookup uses Rust type identity and never requires an interface identifier.
    #[must_use]
    pub fn query_interface<I: CppInterface>(&self) -> Option<InterfaceRef<'_, I>> {
        T::slot_for_type(TypeId::of::<I>()).map(|slot| self.borrow_slot(slot))
    }

    /// Get a directly implemented interface's pointer for a foreign caller.
    #[must_use]
    pub fn as_raw<I: CppInterface>(&self) -> *mut c_void
    where
        T: Implements<I>,
    {
        unsafe { Object::<T>::slot_ptr(self.object.as_ptr(), <T as Implements<I>>::SLOT) }
    }

    /// Transfer allocation ownership to a raw pointer.
    ///
    /// Reclaim it with [`Self::from_raw`] or [`Object::destroy`]. The pointer is the
    /// allocation address, which is also the primary interface address.
    #[must_use]
    pub fn into_raw(self) -> *mut Object<T> {
        let pointer = self.object.as_ptr();
        core::mem::forget(self);
        pointer
    }

    /// Reclaim allocation ownership from a raw pointer.
    ///
    /// # Safety
    ///
    /// `object` must come from [`Self::into_raw`] and still uniquely own a live
    /// allocation. No other owning handle may exist.
    #[must_use]
    pub unsafe fn from_raw(object: *mut Object<T>) -> Self {
        Self {
            object: unsafe { NonNull::new_unchecked(object) },
        }
    }

    fn borrow_slot<I: CppInterface>(&self, slot: usize) -> InterfaceRef<'_, I> {
        let pointer = unsafe { Object::<T>::slot_ptr(self.object.as_ptr(), slot) };
        // Interface's layout contract guarantees that these pointer bytes form I.
        let interface = unsafe { core::ptr::read(core::ptr::from_ref(&pointer).cast::<I>()) };
        InterfaceRef {
            interface,
            lifetime: PhantomData,
        }
    }
}

impl<T: Implement> Deref for OwnedObject<T> {
    type Target = T;

    fn deref(&self) -> &T {
        self.get()
    }
}

impl<T: Implement> Drop for OwnedObject<T> {
    fn drop(&mut self) {
        unsafe { Object::<T>::destroy(self.object.as_ptr()) };
    }
}

// SAFETY: This handle uniquely owns T; all interface views borrow the handle.
unsafe impl<T: Implement + Send> Send for OwnedObject<T> {}
// SAFETY: Shared handle methods expose only shared references to T.
unsafe impl<T: Implement + Sync> Sync for OwnedObject<T> {}

/// Obtain an interface pointer from an implementation method's `self` value.
///
/// # Safety
///
/// `data` must be the implementation field inside a live [`Object<T>`]. A standalone
/// instance of `T` does not satisfy this requirement.
#[must_use]
pub unsafe fn interface_of<T: Implements<I>, I: CppInterface>(data: &T) -> *mut c_void {
    let object = unsafe { Object::<T>::of_data(data) };
    unsafe { Object::<T>::slot_ptr(object, <T as Implements<I>>::SLOT) }
}
