[package]
name = "cppvtable-example"
version.workspace = true
edition.workspace = true
description = "C++ interoperability example for cppvtable"
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
cpp = { workspace = true }
cppvtable = { workspace = true }

[build-dependencies]
cpp_build = { workspace = true }
