[package]
name = "cppvtable-cpp-tests"
version.workspace = true
edition.workspace = true
description = "C and C++ compiler interoperability tests for cppvtable"
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
cpp = { workspace = true }
cppvtable.workspace = true
cppvtable-abi.workspace = true
cppvtable-com.workspace = true

[build-dependencies]
cpp_build = { workspace = true }
cc.workspace = true
